##### Handling missing Values

In [36]:
import numpy as np
import pandas as pd

In [37]:
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Adam', 40, np.nan, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['lynda', 42, 85, np.nan],
               [np.nan, 42, 85, np.nan],
               ['Jenny', np.nan, 100, 25632],
               ['Kenn', np.nan, 110, 25632],
                ['Aly', np.nan, 90, 25582],
               ['John', 41, 85, 1528000]]

df = pd.DataFrame(employee_list, columns=['Name','Age','Weight','Salary'])

In [38]:
rows, cols = df.shape
print(f'Rows:,{rows}')
print(f'Columns:, {cols}')

Rows:,14
Columns:, 4

In [39]:
df.head()

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [40]:
df.isnull().sum()

Name      1
Age       3
Weight    1
Salary    2
dtype: int64

In [41]:
dropped_df = df.dropna()

print(dropped_df)

        Name   Age  Weight     Salary
0      James  36.0    75.0  5428000.0
1    Villers  38.0    74.0  3428000.0
2      VKole  31.0    70.0  8428000.0
3      Smith  34.0    80.0  4428000.0
4      Gayle  40.0   100.0  4528000.0
6     Rooter  33.0    72.0  7028000.0
7   Peterson  42.0    85.0  2528000.0
13      John  41.0    85.0  1528000.0

In [42]:
filled_df = df.fillna('None')

filled_df

        Name   Age Weight     Salary
0      James  36.0   75.0  5428000.0
1    Villers  38.0   74.0  3428000.0
2      VKole  31.0   70.0  8428000.0
3      Smith  34.0   80.0  4428000.0
4      Gayle  40.0  100.0  4528000.0
5       Adam  40.0   None  4528000.0
6     Rooter  33.0   72.0  7028000.0
7   Peterson  42.0   85.0  2528000.0
8      lynda  42.0   85.0       None
9       None  42.0   85.0       None
10     Jenny  None  100.0    25632.0
11      Kenn  None  110.0    25632.0
12       Aly  None   90.0    25582.0
13      John  41.0   85.0  1528000.0

In [43]:
filled_df.isnull().sum()

Name      0
Age       0
Weight    0
Salary    0
dtype: int64

In [44]:
#changing values of certain columns
spec_cols = df[['Weight','Age']].fillna('pending')

spec_cols

     Weight      Age
0      75.0     36.0
1      74.0     38.0
2      70.0     31.0
3      80.0     34.0
4     100.0     40.0
5   pending     40.0
6      72.0     33.0
7      85.0     42.0
8      85.0     42.0
9      85.0     42.0
10    100.0  pending
11    110.0  pending
12     90.0  pending
13     85.0     41.0

In [45]:
df2 = df.fillna(value={'Weight':'Pending', 'Age': 'Unknown', 'Salary':'0.0', 'Name': 'Verif Pending'})

df2

             Name      Age   Weight     Salary
0           James     36.0     75.0  5428000.0
1         Villers     38.0     74.0  3428000.0
2           VKole     31.0     70.0  8428000.0
3           Smith     34.0     80.0  4428000.0
4           Gayle     40.0    100.0  4528000.0
5            Adam     40.0  Pending  4528000.0
6          Rooter     33.0     72.0  7028000.0
7        Peterson     42.0     85.0  2528000.0
8           lynda     42.0     85.0        0.0
9   Verif Pending     42.0     85.0        0.0
10          Jenny  Unknown    100.0    25632.0
11           Kenn  Unknown    110.0    25632.0
12            Aly  Unknown     90.0    25582.0
13           John     41.0     85.0  1528000.0

In [46]:
technologies = {
    'Courses':["Spark",np.nan,"Hadoop","Python","pandas",np.nan,"Java"],
    'Fee' :[20000,25000, np.nan,22000,24000,np.nan,22000],
    'Duration':[np.nan,'40days','35days', np.nan,'60days','50days','55days'],
    'Discount':[1000,np.nan,1500,np.nan,2500,2100,np.nan]
              }

df_tech= pd.DataFrame(technologies)

In [47]:
rows, cols = df_tech.shape

print(rows,cols)

7 4

In [48]:
#count of all missing values
df_tech.isnull().sum()

Courses     2
Fee         2
Duration    2
Discount    3
dtype: int64

In [49]:
df_tech

  Courses      Fee Duration  Discount
0   Spark  20000.0      NaN    1000.0
1     NaN  25000.0   40days       NaN
2  Hadoop      NaN   35days    1500.0
3  Python  22000.0      NaN       NaN
4  pandas  24000.0   60days    2500.0
5     NaN      NaN   50days    2100.0
6    Java  22000.0   55days       NaN

In [54]:
df_tech2 = df_tech.replace(np.nan, '')

df_tech2

  Courses      Fee Duration Discount
0   Spark  20000.0            1000.0
1          25000.0   40days
2  Hadoop            35days   1500.0
3  Python  22000.0
4  pandas  24000.0   60days   2500.0
5                    50days   2100.0
6    Java  22000.0   55days

In [57]:
tech3 = df_tech.replace({'Courses': np.nan, 'Fee': np.nan}, 'PENDING')

tech3

   Courses      Fee Duration  Discount
0    Spark  20000.0      NaN    1000.0
1  PENDING  25000.0   40days       NaN
2   Hadoop  PENDING   35days    1500.0
3   Python  22000.0      NaN       NaN
4   pandas  24000.0   60days    2500.0
5  PENDING  PENDING   50days    2100.0
6     Java  22000.0   55days       NaN

In [59]:
df_tech.fillna('')

  Courses      Fee Duration Discount
0   Spark  20000.0            1000.0
1          25000.0   40days
2  Hadoop            35days   1500.0
3  Python  22000.0
4  pandas  24000.0   60days   2500.0
5                    50days   2100.0
6    Java  22000.0   55days

In [61]:
ep = pd.read_csv(r'pandasLesson_data\data\employee.csv')

ep

        Name   Age  Weight     Salary
0      James  36.0    75.0  5428000.0
1    Villers  38.0    74.0  3428000.0
2      VKole  31.0    70.0  8428000.0
3      Smith  34.0    80.0  4428000.0
4      Gayle  40.0   100.0  4528000.0
5       Adam  40.0     NaN  4528000.0
6     Rooter  33.0    72.0  7028000.0
7   Peterson  42.0    85.0  2528000.0
8      lynda  42.0    85.0        NaN
9        NaN  42.0    85.0        NaN
10     Jenny   NaN   100.0    25632.0
11      Kenn   NaN   110.0    25632.0
12       Aly   NaN    90.0    25582.0
13      John  41.0    85.0  1528000.0
14       Ali  26.0    69.0        NaN

In [ ]:
# count of missing values
ep.isnull().sum()

Name      1
Age       3
Weight    1
Salary    3
dtype: int64

In [65]:
ep = ep.fillna(value= {'Name':'Ver Pending', 'Age': 'Unknown', 'Weight': 'pending', 'Salary':'0.0'})

ep

           Name      Age   Weight     Salary
0         James     36.0     75.0  5428000.0
1       Villers     38.0     74.0  3428000.0
2         VKole     31.0     70.0  8428000.0
3         Smith     34.0     80.0  4428000.0
4         Gayle     40.0    100.0  4528000.0
5          Adam     40.0  pending  4528000.0
6        Rooter     33.0     72.0  7028000.0
7      Peterson     42.0     85.0  2528000.0
8         lynda     42.0     85.0        0.0
9   Ver Pending     42.0     85.0        0.0
10        Jenny  Unknown    100.0    25632.0
11         Kenn  Unknown    110.0    25632.0
12          Aly  Unknown     90.0    25582.0
13         John     41.0     85.0  1528000.0
14          Ali     26.0     69.0        0.0